name: '@srclaunch/web-application-state'
description: Redux state and utilities used by AppLab web applications
author: Steven Bennett <steven@srclaunch.com>
license: MIT
version: 0.1.76
engines:
  node: '>=16'
  yarn: '>=3.2.0'
publishConfig:
  access: public
  registry: https://registry.npmjs.org/
type: module
main: ./dist/index.mjs
types: ./dist/index.d.ts
files:
  - package.json
  - dist
module: ./dist/index.mjs
exports:
  .:
    import: ./dist/index.mjs
    require: ./dist/index.umd.cjs
scripts:
  build: yarn srclaunch build
  qr: >-
    yarn srclaunch changesets add --files "." --message "Quick release" --type
    "chore" && yarn srclaunch release --push
  release: yarn srclaunch release
  test: yarn srclaunch test
  test:watch: yarn srclaunch test --watch
  test:coverage: yarn srclaunch test --coverage
  yui: yarn upgrade-interactive
peerDependencies:
  react: 18.1.0
  react-dom: 18.1.0
  styled-components: 5.3.5
dependencies:
  '@reduxjs/toolkit': 1.8.1
  '@srclaunch/exceptions': 0.1.72
  '@srclaunch/http-client': 0.1.23
  '@srclaunch/i18n': 0.1.7
  '@srclaunch/logger': 0.1.87
  '@srclaunch/themes': 0.1.36
  '@srclaunch/validation': 0.1.29
  '@srclaunch/web-environment': 0.1.33
  amazon-cognito-identity-js: 5.2.8
  crypto-js: 4.1.1
  history: 5.3.0
  luxon: 2.3.2
  nanoid: 3.3.4
  react-redux: 8.0.1
  react-router: 6.3.0
  react-router-dom: 6.3.0
  redux: 4.2.0
devDependencies:
  '@microsoft/eslint-plugin-sdl': 0.2.0
  '@srclaunch/cli': 0.1.484
  '@srclaunch/dx': 0.1.52
  '@srclaunch/types': 0.1.171
  '@testing-library/jest-dom': 5.16.4
  '@testing-library/react': 13.2.0
  '@testing-library/user-event': 14.1.1
  '@types/jest': 27.5.0
  '@types/node': 17.0.31
  '@typescript-eslint/eslint-plugin': 5.22.0
  '@typescript-eslint/parser': 5.22.0
  c8: 7.11.2
  eslint: 8.15.0
  eslint-config-prettier: 8.5.0
  eslint-import-resolver-typescript: 2.7.1
  eslint-plugin-eslint-comments: 3.2.0
  eslint-plugin-functional: 4.2.1
  eslint-plugin-import: 2.26.0
  eslint-plugin-jest: 26.1.5
  eslint-plugin-node: 11.1.0
  eslint-plugin-only-warn: 1.0.3
  eslint-plugin-prettier: 4.0.0
  eslint-plugin-regexp: 1.7.0
  eslint-plugin-simple-import-sort: 7.0.0
  eslint-plugin-sort-keys-fix: 1.1.2
  eslint-plugin-sort-requires: 2.1.0
  eslint-plugin-testing-library: 5.3.1
  eslint-plugin-unicorn: 42.0.0
  prettier: 2.6.2
  standard-version: 9.3.2
  ts-jest: 27.1.4
  typescript: 4.6.4
